name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: package
      run: |
        PATH="/opt/apache-maven-3.6.3/bin:$PATH"
        mvn clean install -DskipTests=true
    - name: docker image build
      run: |
        docker build -t 20.193.156.188:8085/first-img:1.0 .
        docker login -u admin 20.193.156.188:8085 -p ${{ secrets.NEXUS_PASSWORD }}
        docker push 20.193.156.188:8085/first-img:1.0
